### ISSUE TITLE
Broken API service?

### ISSUE THREAD

**Issue by sphakka** [OpenPGP/openpgp.org#104]
It looks like the API service is broken. <https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=foobar> returns
> Error 400 Invalid request

**Comment by teythoon** [comment]
It also points to https://keys.openpgp.org/about/api which says:

> Hagrid implements a subset of the [HKP](https://tools.ietf.org/html/draft-shaw-openpgp-hkp-00) protocol so that tools like GnuPG and OpenKeychain can use it without modification.

Notably, that subset only allows queries for email addresses, key IDs, and fingerprints.  Note how appending `@example.org` to your query makes it work:

https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=foobar@example.org
