### ISSUE TITLE
Use Content-Security-Policy

### ISSUE THREAD

**Issue by war59312** [OpenPGP/openpgp.org#19]
Hi,

Please enhance the security of the website.

D on https://securityheaders.io/?q=openpgp.org&followRedirects=on and https://observatory.mozilla.org/analyze.html?host=openpgp.org

Should be able to fix these issues in just a few minutes time.

Thanks,

Will

**Comment by dschuermann** [comment]
Thanks for the pointers. I am no expert in these headers.
I got all working except ``Content-Security-Policy``.

I used the simple rule ``Content-Security-Policy: default-src 'self';`` but even with this the background image of the template is gone. As far as I understand and have seen using Chrome's debug tools, no external CDNs are used (as I intended) thus everything should be served from 'self'.

Do you have an idea?

**Comment by war59312** [comment]
I believe you need to use:

`add_header Content-Security-Policy "frame-ancestors 'none'; base-uri 'self'; default-src 'none'; script-src 'self'; img-src 'self'; style-src 'self'; font-src 'self' data:; frame-src 'self'; object-src 'none'"; font-src 'self';`

This allows stylesheet (main.css), images, and javascript (main.min.js), and the font (fontawesome-webfont.woff2?v=4..3) to work correctly.

That should do it, if not please let me know what "errors" or warnings you see in chrome debug window.

**Comment by dschuermann** [comment]
Your rules also does not work. Actually it is even stricter than mine AFAIK because some stuff is disabled by using 'none'. Mine sets all on 'self'.

I will leave the headers for now. This is a static site, so AFAIK the potential for misuse is small.

**Comment by dschuermann** [comment]
I over-read your comment about the Chrome debug window. This helped a lot. I got a working policy now.

**Comment by war59312** [comment]
Ok, I was trying not to use "unsafe-inline", but your right. Better than nothing. Good job.

What broke with mine above, I'm curious?

**Comment by dschuermann** [comment]
The Image on the front page
