### ISSUE TITLE
Protonmail for Android

### ISSUE THREAD

**Issue by ruiamar** [OpenPGP/openpgp.org#20]
There is a version of Protonmail for Android. I use it and its fine. Perhaps you must include it in "https://www.openpgp.org/software/ ". 

See here:

https://play.google.com/store/apps/details?id=ch.protonmail.android&hl=en

**Comment by dschuermann** [comment]
Should we really included it? It cannot communicate with contacts outside of protonmail: https://protonmail.com/support/knowledge-base/sending-a-message-using-pgppgp/

**Comment by dschuermann** [comment]
I will probably not add it to the Android section as their client does not support sending OpenPGP encrypted emails.

**Comment by ruiamar** [comment]
Yes. You are wright. It's very important OpenPGP. 
Thank you
