### ISSUE TITLE
Missing app in the list of email client supporting PGP encryption

### ISSUE THREAD

**Issue by Krukskul** [OpenPGP/openpgp.org#25]
We use in our office email client / file manager called EverDesk. It has totally transparent and trouble-free true end-to-end PGP encryption (best implementation after we tried Outlook and TB), which is huge improvement comparing to other apps. One of the best thing is that encrypts everything on the fly, which means all the mail and attachments remain unencrypted on the computer - regardless sent or received. BUT! It is not free (although worth every penny) and it is only for Windows (not a problem for our office since we all work on Windows machines).

**Comment by dschuermann** [comment]
Please make a pull request to add this software :)

**Comment by Krukskul** [comment]
Hi Dominik,
Thanks for the response. Unfortunately my IQ doesn't allow me to figure out how to add a pull request. After opening the New Pull Request form, I am lost at the very top in what to compare with what :)
Nevermind, I just wanted to update the list of email clients for people to know. If EverDesk is not there - no big deal 👍 
Cheers,
Danny

**Comment by dschuermann** [comment]
done in https://github.com/OpenPGP/openpgp.org/commit/ec64ad5c894bab63af106544a190727c46487d6f
