### ISSUE TITLE
Signature isn't selected when trying to sign during export of PDF-file in LibreOffice Writer

### ISSUE THREAD

**Issue by HeRo002** [OpenPGP/openpgp.org#31]
NB! I am sorry if this is the wrong forum for this problem, but I have asked the same question in https://ask.libreoffice.org/en/question/183723/signature-isnt-selected-when-trying-to-sign-during-export-of-pdf-file-in-writer/ without any reaction whatsoever: 

I have an Enigmail PGP signature that I use in Thunderbird under Ubuntu Linux. In Libre Office I can use it to sign (and encrypt) an ODT-document. But when I try to use it during export of a document as a PDF document something goes wrong. In the 'PDF Options' window on the 'Digital Signature' tab, I click on the 'Select' button and get the 'Select Certificate' window. My signature is already selected (it's the only one present). I now click on 'Sign'. The window closes, but the signature isn't shown in the field called "Use this certificate to digitally sign PDF documents:". So when I press the 'Export' button, I get a "signature generation failed" error message, and export of the PDF file fails.

Can anyone help me please? Thank you. 

Best regards, Henrik

**Comment by dschuermann** [comment]
Hi Henrik,

this is indeed the wrong forum. This issue tracker is only for issues related to the website openpgp.org, not related to software.

**Comment by HeRo002** [comment]
I am sorry! 
Do you have any idea about where to post this problem?
