### ISSUE TITLE
Key Server should revalidate all mail adresses every few months

### ISSUE THREAD

**Issue by RichardEb** [OpenPGP/openpgp.org#34]
The Key Server should revalidate all mail adresses every few months.
Mail adresses can expire: Many free hosters delete unused adresses. Paid providers that don't offer free options delete the adresse as well as Webhoster. 

PGP certificates can live long. So it is possible that at some point in the future the owner of the private key and the owner of the adress are two different persons.

**Comment by dschuermann** [comment]
Hagrid discussions are here: https://gitlab.com/hagrid-keyserver/hagrid/issues
