### ISSUE TITLE
No Valid OpenPGP

### ISSUE THREAD

**Issue by vertinard** [OpenPGP/openpgp.org#55]
I tried getting the key for opera using this : 

`wget -qO- https://deb.opera.com/archive.key | sudo apt-key add -`

but what I got in response was this : 

gpg: no valid OpenPGP data found.

Can someone help me fox this ? 

I run Linux Mint 20

**Comment by dschuermann** [comment]
Please use the gnupg bug tracker: https://gnupg.org/documentation/bts.html
