### ISSUE TITLE
Include Courier MTA's webmail SqWebMail as PGP online software

### ISSUE THREAD

**Issue by gnusupport** [OpenPGP/openpgp.org#57]
I am using since ages SqWebMail as self hosted system and it includes PGP key generation and encryption. Please include it on https://www.openpgp.org/software/

Reference: https://www.courier-mta.org/sqwebmail/screenshots.html

**Comment by dschuermann** [comment]
Please make a pull request.

**Comment by gnusupport** [comment]
* Dominik Schürmann <notifications@github.com> [2020-10-27 16:35]:
> Please make a pull request.

You may just link the words:

SqWebmail from Courier MTA

to the link: http://www.courier-mta.org/sqwebmail/
