### ISSUE TITLE
Thunderbird doesn't use Enigmail anymore

### ISSUE THREAD

**Issue by masvil** [OpenPGP/openpgp.org#58]
Thunderbird doesn't use Enigmail anymore as stated here: https://sourceforge.net/p/enigmail/forum/announce/thread/248bfafc3f/

Please evaluate to fix that on https://www.openpgp.org/software/

**Comment by jjj0** [comment]
I opened a pull request to change that

**Comment by jjj0** [comment]
solved in #70 
I forgot to link this issue, but it should be closed now.
