### ISSUE TITLE
Adding flipdog on the softwares list

### ISSUE THREAD

**Issue by InfoLibre** [OpenPGP/openpgp.org#67]
I suggest to add https://play.google.com/store/apps/details?id=com.flipdog.crypto.plugin&hl=en on https://www.openpgp.org/software/

**Comment by andrewgdotcom** [comment]
The link appears dead, and various places around the internet would indicate that it is no longer under active development. I do see that the Maildroid app page mentions an "email encryption plugin" but has no link.
