### ISSUE TITLE
add tutamail 

### ISSUE THREAD

**Issue by rafy** [OpenPGP/openpgp.org#72]
i want like tutamail to be added to the list

**Comment by SethFalco** [comment]
I assume Tutamail refers to Tutanota.

> one of our domains (tutanota.com, tutanota.de, **tutamail.com**, tuta.io, keemail.me
> 
> ­— https://tutanota.com/faq/

Tutanota doesn't use PGP for encryption, it implements a custom protocol which is not interoperable with other clients/services.

More Info:
* https://tutanota.com/faq/#pgp
* https://tutanota.com/blog/posts/innovative-encryption#why-tutanota-does-not-rely-on-pgp

For better or for worse, they basically sacrificed interoperability and user choice/control, in favor of taking privacy a step further.

Tutanota should not be listed in this repository, however.

**Comment by dkg** [comment]
If the goal is encrypted subject lines, there are [standards-based ways to achieve that interoperably](https://datatracker.ietf.org/doc/draft-ietf-lamps-header-protection/) which work fine with 
OpenPGP.  I agree that if Tutanota doesn't use OpenPGP, it should not be included in a list of OpenPGP implementations.

**Comment by teythoon** [comment]
They still don't implement OpenPGP, so I'm going to close this issue.
