### ISSUE TITLE
Remove deprecated iOS app from recommendations

### ISSUE THREAD

**Issue by MartPiet** [OpenPGP/openpgp.org#81]
"Safe Easy Privacy" is not available in the App Store anymore. Even the website link is not working anymore. 

https://www.openpgp.org/software/safe/

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 02/09/2022, 22:28, ***@***.*** wrote:"Safe Easy Privacy" is not available in the App Store anymore. Even the website link is not working anymore.
https://www.openpgp.org/software/safe/

**Comment by dschuermann** [comment]
feel free to open a pull request.

**Comment by joedemcher** [comment]
Just did that so this issue can be closed. #122 

> feel free to open a pull request.
