### ISSUE TITLE
https://keys.openpgp.org/manage gives "500: Internal Server Error"

### ISSUE THREAD

**Issue by bwildenhain** [OpenPGP/openpgp.org#87]
I tried to remove my expired key but I only got the following message at https://keys.openpgp.org/manage:

500: Internal Server Error

The server encountered an internal error while processing this request.

------------------------------------------------------------------------------------------------------------
Rocket

**Comment by drschrisjacobs** [comment]
I got the same error with my valid key

**Comment by Valodim** [comment]
Hey folks. This is not the right issue tracker for keys.openpgp.org, please report issues over at https://gitlab.com/keys.openpgp.org/hagrid/-/merge_requests

That said, I was able to reproduce the issue mentioned here, it will be fixed in a short while. Thanks for reporting :ok_hand:
